return function()
    loveframes = require 'libraries.loveframes'
    moonshine = require 'libraries.moonshine'
    slab = require 'libraries.slab'
    sti = require 'libraries.sti'
    sunlight = require 'libraries.sunlight'
    camera = require 'libraries.camera'
    cartographer = require 'libraries.cartographer'
    collision = require 'libraries.collision'
    deep = require 'libraries.deep'
    gamestate = require 'libraries.gamestate'
    gamejolt = require 'libraries.gamejolt'
    json = require 'libraries.json'
    lume = require 'libraries.lume'
    lue = require 'libraries.lue'
    push = require 'libraries.push'
    neuron = require 'libraries.neuron'
    nativefs = require 'libraries.nativefs'
    timer = require 'libraries.timer'
    xml = require 'libraries.xml'
end